# Generated by Django 4.2.7 on 2025-09-13 00:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="client",
            name="current_plan",
            field=models.CharField(
                blank=True,
                choices=[
                    ("starter", "Starter"),
                    ("pro", "Pro"),
                    ("premium", "Premium"),
                ],
                max_length=50,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="client",
            name="stripe_customer_id",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="client",
            name="stripe_subscription_id",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="client",
            name="subscription_end_date",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="client",
            name="subscription_start_date",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="client",
            name="trial_end_date",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
