# Generated by Django 4.2.7 on 2025-11-10 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_add_agent_role_and_model'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='agent',
            options={'ordering': ['-created_at']},
        ),
        migrations.RemoveField(
            model_name='client',
            name='account_manager',
        ),
        migrations.AlterField(
            model_name='agent',
            name='department',
            field=models.CharField(choices=[('marketing', 'Marketing'), ('website', 'Website Development')], default='marketing', max_length=50),
        ),
    ]
