# Generated by Django 4.2.7 on 2025-11-11 01:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_agent_options_remove_client_account_manager_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RedeemCode',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(help_text='Unique redemption code', max_length=50, unique=True)),
                ('value', models.DecimalField(decimal_places=2, help_text='Credit amount', max_digits=10)),
                ('description', models.TextField(blank=True, help_text='Internal description of the code purpose')),
                ('is_active', models.BooleanField(default=True)),
                ('usage_limit', models.IntegerField(default=1, help_text='How many times this code can be used')),
                ('times_used', models.IntegerField(default=0)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_redeem_codes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RedeemCodeUsage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('redeemed_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('redeem_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usages', to='api.redeemcode')),
                ('transaction', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.transaction')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='redeemed_codes', to=settings.AUTH_USER_MODEL)),
                ('wallet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='redeem_usages', to='api.wallet')),
            ],
            options={
                'ordering': ['-redeemed_at'],
                'unique_together': {('redeem_code', 'user')},
            },
        ),
    ]
