# Generated by Django 4.2.7 on 2025-11-11 07:08

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_redeemcode_redeemcodeusage'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='active_services',
            field=models.JSONField(default=list, help_text='List of active services for this client: marketing, website, courses'),
        ),
        migrations.CreateModel(
            name='ClientServiceSettings',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('service_type', models.CharField(choices=[('marketing', 'Marketing'), ('website', 'Website Builder'), ('courses', 'Courses')], max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('settings', models.JSONField(default=dict, help_text='Service-specific configuration and preferences')),
                ('activation_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('deactivation_date', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_agent', models.ForeignKey(blank=True, help_text='Agent assigned for this specific service', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='service_clients', to='api.agent')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service_settings', to='api.client')),
            ],
            options={
                'verbose_name': 'Client Service Setting',
                'verbose_name_plural': 'Client Service Settings',
                'ordering': ['-created_at'],
                'unique_together': {('client', 'service_type')},
            },
        ),
    ]
