# Generated by Django 4.2.7 on 2025-11-11 07:27

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_client_active_services_clientservicesettings'),
    ]

    operations = [
        migrations.CreateModel(
            name='WebsiteTemplate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('category', models.CharField(choices=[('business', 'Business'), ('ecommerce', 'E-Commerce'), ('portfolio', 'Portfolio'), ('blog', 'Blog'), ('restaurant', 'Restaurant'), ('healthcare', 'Healthcare'), ('education', 'Education'), ('real_estate', 'Real Estate'), ('agency', 'Agency'), ('other', 'Other')], max_length=50)),
                ('preview_url', models.URLField(help_text='Live preview URL')),
                ('thumbnail_url', models.URLField(help_text='Thumbnail image URL')),
                ('screenshots', models.JSONField(default=list, help_text='List of screenshot URLs')),
                ('features', models.JSONField(default=list, help_text='List of template features')),
                ('tech_stack', models.JSONField(default=list, help_text='Technologies used')),
                ('is_active', models.BooleanField(default=True)),
                ('complexity_score', models.IntegerField(default=5, help_text='Complexity from 1-10')),
                ('base_price', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['category', 'name'],
            },
        ),
        migrations.AddField(
            model_name='websiteproject',
            name='template_customizations',
            field=models.JSONField(default=dict, help_text='Template customization settings'),
        ),
        migrations.CreateModel(
            name='WebsiteSEO',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('google_search_console_connected', models.BooleanField(default=False)),
                ('gsc_property_url', models.URLField(blank=True)),
                ('target_keywords', models.JSONField(default=list, help_text='List of target keywords')),
                ('current_rankings', models.JSONField(default=dict, help_text='Keyword rankings data')),
                ('backlinks_count', models.IntegerField(default=0)),
                ('domain_authority', models.IntegerField(default=0, help_text='0-100 score')),
                ('page_speed_score', models.IntegerField(default=0, help_text='0-100 score')),
                ('seo_score', models.IntegerField(default=0, help_text='Overall SEO score 0-100')),
                ('last_audit_date', models.DateTimeField(blank=True, null=True)),
                ('audit_results', models.JSONField(default=dict, help_text='Latest SEO audit results')),
                ('critical_issues', models.IntegerField(default=0)),
                ('warnings', models.IntegerField(default=0)),
                ('recommendations', models.JSONField(default=list)),
                ('organic_traffic', models.IntegerField(default=0, help_text='Monthly organic visits')),
                ('indexed_pages', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('project', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='seo', to='api.websiteproject')),
            ],
            options={
                'verbose_name': 'Website SEO',
                'verbose_name_plural': 'Website SEO',
            },
        ),
        migrations.CreateModel(
            name='WebsiteHosting',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('domain_name', models.CharField(blank=True, max_length=255)),
                ('domain_provider', models.CharField(blank=True, choices=[('namecheap', 'Namecheap'), ('godaddy', 'GoDaddy'), ('cloudflare', 'Cloudflare'), ('google', 'Google Domains'), ('other', 'Other')], max_length=100)),
                ('domain_purchased_at', models.DateTimeField(blank=True, null=True)),
                ('domain_expires_at', models.DateTimeField(blank=True, null=True)),
                ('domain_auto_renew', models.BooleanField(default=True)),
                ('hosting_provider', models.CharField(blank=True, choices=[('vercel', 'Vercel'), ('netlify', 'Netlify'), ('aws', 'AWS'), ('digitalocean', 'DigitalOcean'), ('cloudflare', 'Cloudflare Pages'), ('other', 'Other')], max_length=100)),
                ('hosting_plan', models.CharField(blank=True, max_length=100)),
                ('hosting_url', models.URLField(blank=True, help_text='Hosting control panel URL')),
                ('ssl_status', models.CharField(choices=[('pending', 'Pending'), ('active', 'Active'), ('expired', 'Expired'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('ssl_expires_at', models.DateTimeField(blank=True, null=True)),
                ('dns_configured', models.BooleanField(default=False)),
                ('nameservers', models.JSONField(default=list, help_text='List of nameserver addresses')),
                ('deployment_url', models.URLField(blank=True, help_text='Live website URL')),
                ('last_deployed_at', models.DateTimeField(blank=True, null=True)),
                ('hosting_credentials', models.JSONField(default=dict, help_text='Encrypted hosting credentials')),
                ('domain_credentials', models.JSONField(default=dict, help_text='Encrypted domain credentials')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('project', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='hosting', to='api.websiteproject')),
            ],
            options={
                'verbose_name': 'Website Hosting',
                'verbose_name_plural': 'Website Hosting',
            },
        ),
        migrations.AddField(
            model_name='websiteproject',
            name='selected_template',
            field=models.ForeignKey(blank=True, help_text='Selected template for this project', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='projects', to='api.websitetemplate'),
        ),
    ]
