# Generated by Django 4.2.7 on 2025-11-11 07:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_websitetemplate_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='allow_individual_purchase',
            field=models.BooleanField(default=True, help_text='Allow purchase without subscription'),
        ),
        migrations.AddField(
            model_name='course',
            name='is_free',
            field=models.BooleanField(default=False, help_text='Course is free for everyone'),
        ),
        migrations.AddField(
            model_name='course',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Price for individual course purchase', max_digits=10),
        ),
        migrations.CreateModel(
            name='CoursePurchase',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('amount_paid', models.DecimalField(decimal_places=2, max_digits=10)),
                ('payment_method', models.CharField(default='paypal', help_text='paypal, wallet, etc', max_length=50)),
                ('access_expires_at', models.DateTimeField(blank=True, help_text='Null = lifetime access', null=True)),
                ('is_refunded', models.BooleanField(default=False)),
                ('refunded_at', models.DateTimeField(blank=True, null=True)),
                ('refund_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('paypal_order_id', models.CharField(blank=True, help_text='PayPal order ID', max_length=255)),
                ('paypal_payer_id', models.CharField(blank=True, help_text='PayPal payer ID', max_length=255)),
                ('purchased_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('last_accessed_at', models.DateTimeField(blank=True, null=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purchases', to='api.course')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course_purchases', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Course Purchase',
                'verbose_name_plural': 'Course Purchases',
                'ordering': ['-purchased_at'],
                'unique_together': {('user', 'course')},
            },
        ),
    ]
