# Generated by Django 4.2.7 on 2025-11-11 08:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0009_course_allow_individual_purchase_course_is_free_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="websiteproject",
            name="additional_notes",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="websiteproject",
            name="budget_range",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="websiteproject",
            name="content_requirements",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="websiteproject",
            name="timeline_expectations",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name="websiteproject",
            name="preferred_style",
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
