# Generated by Django 4.2.7 on 2025-11-11 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_websiteproject_additional_notes_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('task_assigned', 'Task Assigned'), ('task_completed', 'Task Completed'), ('task_overdue', 'Task Overdue'), ('payment_due', 'Payment Due'), ('payment_received', 'Payment Received'), ('payment_verification', 'Payment Verification'), ('invoice_created', 'Invoice Created'), ('invoice_overdue', 'Invoice Overdue'), ('invoice_reminder', 'Invoice Reminder'), ('content_submitted', 'Content Submitted'), ('content_approved', 'Content Approved'), ('content_rejected', 'Content Rejected'), ('content_posted', 'Content Posted'), ('message_received', 'Message Received'), ('website_phase_completed', 'Website Phase Completed'), ('website_demo_ready', 'Website Demo Ready'), ('course_enrollment', 'Course Enrollment'), ('course_completed', 'Course Completed'), ('subscription_activated', 'Subscription Activated'), ('subscription_created', 'Subscription Created'), ('subscription_cancelled', 'Subscription Cancelled'), ('subscription_renewal', 'Subscription Renewal'), ('user_registered', 'User Registered'), ('performance_update', 'Performance Update'), ('general', 'General')], max_length=30),
        ),
    ]
