# Generated by Django 4.2.7 on 2025-11-11 10:21

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_update_notification_types'),
    ]

    operations = [
        migrations.CreateModel(
            name='Campaign',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('platform', models.CharField(choices=[('instagram', 'Instagram'), ('youtube', 'YouTube'), ('tiktok', 'TikTok'), ('multi', 'Multi-Platform')], max_length=20)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('scheduled', 'Scheduled'), ('active', 'Active'), ('paused', 'Paused'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='draft', max_length=20)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('goal', models.TextField(help_text='Campaign objective/goal')),
                ('target_audience', models.TextField(blank=True)),
                ('target_reach', models.IntegerField(default=0, help_text='Target reach/impressions')),
                ('target_engagement', models.IntegerField(default=0, help_text='Target engagement count')),
                ('budget', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('actual_reach', models.IntegerField(default=0)),
                ('actual_engagement', models.IntegerField(default=0)),
                ('actual_spend', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('agent', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='campaigns', to='api.agent')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='campaigns', to='api.client')),
                ('content_posts', models.ManyToManyField(blank=True, related_name='campaigns', to='api.contentpost')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='WebsiteVersion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('version_number', models.CharField(help_text='e.g., v1.0, v1.1, v2.0', max_length=50)),
                ('status', models.CharField(choices=[('uploaded', 'Uploaded'), ('testing', 'Testing'), ('approved', 'Approved'), ('deployed', 'Deployed'), ('rejected', 'Rejected')], default='uploaded', max_length=20)),
                ('file', models.FileField(help_text='Zip file containing website files', upload_to='website_versions/%Y/%m/')),
                ('file_size', models.BigIntegerField(help_text='File size in bytes')),
                ('preview_url', models.URLField(blank=True, help_text='URL where this version can be previewed')),
                ('deployment_url', models.URLField(blank=True, help_text='Live deployment URL')),
                ('notes', models.TextField(blank=True, help_text='Agent notes about this version')),
                ('client_feedback', models.TextField(blank=True, help_text='Client feedback on this version')),
                ('technologies_used', models.JSONField(default=list, help_text='List of technologies/frameworks used')),
                ('changelog', models.TextField(blank=True, help_text='List of changes in this version')),
                ('uploaded_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('deployed_at', models.DateTimeField(blank=True, null=True)),
                ('agent', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_versions', to='api.agent')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='api.websiteproject')),
            ],
            options={
                'ordering': ['-uploaded_at'],
                'unique_together': {('project', 'version_number')},
            },
        ),
    ]
