# Generated by Django 4.2.7 on 2025-11-11 13:14

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0013_contentschedule"),
    ]

    operations = [
        migrations.AddField(
            model_name="transaction",
            name="paid_for_service",
            field=models.CharField(
                blank=True,
                help_text="What service was paid for: course_id, subscription, invoice_id, etc.",
                max_length=100,
            ),
        ),
        migrations.CreateModel(
            name="WalletAutoRecharge",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "is_enabled",
                    models.BooleanField(
                        default=False, help_text="Enable/disable auto-recharge"
                    ),
                ),
                (
                    "threshold_amount",
                    models.DecimalField(
                        decimal_places=2,
                        default=10.0,
                        help_text="Recharge when balance falls below this amount",
                        max_digits=10,
                    ),
                ),
                (
                    "recharge_amount",
                    models.DecimalField(
                        decimal_places=2,
                        default=50.0,
                        help_text="Amount to add when auto-recharging",
                        max_digits=10,
                    ),
                ),
                (
                    "payment_method_id",
                    models.CharField(
                        blank=True,
                        help_text="PayPal subscription ID or saved payment method ID",
                        max_length=255,
                    ),
                ),
                (
                    "payment_method_type",
                    models.CharField(
                        choices=[("paypal", "PayPal"), ("card", "Credit Card")],
                        default="paypal",
                        max_length=50,
                    ),
                ),
                ("last_recharge_date", models.DateTimeField(blank=True, null=True)),
                ("total_recharges", models.IntegerField(default=0)),
                (
                    "total_recharged_amount",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "wallet",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="auto_recharge",
                        to="api.wallet",
                    ),
                ),
            ],
            options={
                "verbose_name": "Wallet Auto-Recharge",
                "verbose_name_plural": "Wallet Auto-Recharges",
            },
        ),
    ]
