# Generated by Django 4.2.7 on 2025-11-11 20:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0015_clientaccessrequest"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="clientaccessrequest",
            unique_together=set(),
        ),
        migrations.AddField(
            model_name="clientaccessrequest",
            name="service_type",
            field=models.CharField(
                choices=[
                    ("marketing", "Marketing"),
                    ("website", "Website Development"),
                ],
                default="marketing",
                help_text="Service type for this request",
                max_length=20,
            ),
        ),
        migrations.AlterUniqueTogether(
            name="clientaccessrequest",
            unique_together={("agent", "client", "service_type", "status")},
        ),
    ]
