# Generated by Django 4.2.7 on 2025-11-13 10:50

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0016_alter_clientaccessrequest_unique_together_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="ContentRequest",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "platform",
                    models.CharField(
                        choices=[
                            ("instagram", "Instagram"),
                            ("youtube", "YouTube"),
                            ("tiktok", "TikTok"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        help_text="Brief title for the request", max_length=255
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        help_text="Detailed description of content wanted"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("in-progress", "In Progress"),
                            ("completed", "Completed"),
                            ("rejected", "Rejected"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                (
                    "preferred_date",
                    models.DateField(
                        blank=True, help_text="Preferred posting date", null=True
                    ),
                ),
                (
                    "notes",
                    models.TextField(
                        blank=True,
                        help_text="Additional notes or requirements from client",
                    ),
                ),
                (
                    "agent_notes",
                    models.TextField(blank=True, help_text="Notes from agent"),
                ),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "client",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="content_requests",
                        to="api.client",
                    ),
                ),
                (
                    "created_content",
                    models.OneToOneField(
                        blank=True,
                        help_text="The content post created from this request",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="source_request",
                        to="api.contentpost",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ContentRequestImage",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("image", models.ImageField(upload_to="content_request_images/%Y/%m/")),
                ("caption", models.CharField(blank=True, max_length=255)),
                ("order", models.IntegerField(default=0)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "content_request",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reference_images",
                        to="api.contentrequest",
                    ),
                ),
            ],
            options={
                "ordering": ["order", "created_at"],
            },
        ),
    ]
