# Generated by Django 4.2.7 on 2025-11-13 10:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0017_contentrequest_contentrequestimage"),
    ]

    operations = [
        migrations.AddField(
            model_name="client",
            name="marketing_agent",
            field=models.ForeignKey(
                blank=True,
                help_text="Marketing agent assigned to manage social media for this client",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="marketing_clients",
                to="api.agent",
            ),
        ),
        migrations.AddField(
            model_name="client",
            name="website_agent",
            field=models.ForeignKey(
                blank=True,
                help_text="Website agent assigned to manage website projects for this client",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="website_clients",
                to="api.agent",
            ),
        ),
    ]
